name: Compile all collections into compendiums
on: 
  push:
    branches: [ master ]
    tags:
      - '*'
  workflow_dispatch:
  pull_request:

jobs:
  compile_collections:
    name: Compile collections
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install xsltproc and parallel
        run: |
          sudo apt-get update
          sudo apt-get install -y xsltproc parallels

      - name: Compile collections into compendiums in parallel
        run: |
          set -euxo pipefail
          trap 'echo "Error occurred during compilation!"' ERR

          mkdir -p Compendiums
          # Use GNU parallel to compile XML files concurrently (4 jobs in parallel)
          find Collections -name '*.xml' | parallel -j 4 '
            filename=$(basename {});
            xsltproc -o "Compendiums/$filename" "Utilities/merge.xslt" "{}"
          '

      - name: Zip up compendiums
        run: zip -r compendiums.zip Compendiums/*.xml

      - name: Upload compiled XML files as artifact
        uses: actions/upload-artifact@v4
        with: 
          name: compendiums-xml-${{ github.ref_name }}
          path: Compendiums/

      - name: Upload zipped compendiums as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compendiums-zip-${{ github.ref_name }}
          path: compendiums.zip

      # Create a GitHub release when a tag is pushed
      - name: Create versioned release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: Compendiums/*

      # Update the nightly release only on master branch push
      - name: Update nightly release
        if: github.ref == 'refs/heads/master'
        uses: pyTooling/Actions/releaser@main
        with:
          tag: nightly
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: Compendiums/*
