name: Compile all collections into compendiums
on: 
  push:
    branches: [ master ]
    tags:
      - '*'
  workflow_dispatch:
  pull_request:

jobs:
  compile_collections:
    name: Compile collections
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install xsltproc and parallel
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: xsltproc
          version: 1.0

      - name: Compile collections into compendiums (with [Stripped] if applicable)
        run: |
          set -euxo pipefail
          trap 'echo "Error occurred during compilation!"' ERR

          mkdir -p Compendiums

          for f in Collections/*.xml; do
            filename=$(basename "$f")
            output="Compendiums/$filename"

            echo "Compiling $filename ..."
            xsltproc --xinclude -o "$output" "Utilities/merge.xslt" "$f"

            # Check for '2024' and not '2014' in the filename
            if [[ "$filename" == *2024* && "$filename" != *2014* ]]; then
              stripped_name="${filename%.xml}_[STRIPPED].xml"
              stripped_output="Compendiums/$stripped_name"

              echo "Creating stripped version: $stripped_name"
              cp "$output" "$stripped_output"

              # Remove [2024] tags (compatible with both GNU and BSD/macOS sed)
              if sed --version >/dev/null 2>&1; then
                sed -i 's/ \[2024\]//g' "$stripped_output"
              else
                sed -i '' 's/ \[2024\]//g' "$stripped_output"
              fi
            fi
          done

      - name: Upload compiled XML files as artifact
        uses: actions/upload-artifact@v4
        with: 
          name: compendiums-${{ github.ref_name }}
          path: Compendiums/

      # Create a GitHub release when a tag is pushed
      - name: Create versioned release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: Compendiums/*

      # Update the nightly release only on master branch push
      - name: Update nightly release
        if: github.ref == 'refs/heads/master'
        uses: pyTooling/Actions/releaser@main
        with:
          tag: nightly
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: Compendiums/*
